export const COMPANY_HEAD_DATA = [
	{ title: "Company name", className: "" },
	{ title: "Address", className: "" },
	{ title: "Contact person", className: "" },
	{ title: "Email", className: "" },
	{ title: "Contact", className: "" },
	{ title: "Action", className: "" },
];

export const DRIVERS_HEAD_DATA = [
	{ title: "Driver name", className: "" },
	{ title: "Mobile number", className: "" },
	{ title: "Route", className: "" },
	{ title: "City", className: "" },
	{ title: "Email", className: "" },
	{ title: "Onboarded", className: "" },
	{ title: "Status", className: "" },
	{ title: "Rating", className: "" },
	{ title: "Action", className: "" },
];

export const EMPLOYEES_HEAD_DATA = [
	{ title: "Employee", className: "" },
	{ title: "Email", className: "" },
	{ title: "Mobile number", className: "" },
	{ title: "City", className: "" },
	{ title: "Address", className: "" },
	{ title: "Route", className: "" },
	{ title: "Action", className: "" },
];

export const VEHICLES_HEAD_DATA = [
	{ title: "Registration #", className: "" },
	{ title: "Register with", className: "" },
	{ title: "Mobile number", className: "" },
	{ title: "Registration city", className: "" },
	{ title: "Address", className: "" },
	{ title: "Driver", className: "" },
	{ title: "Action", className: "" },
];

export const ROUTE_HEAD_DATA = [
	{ title: "Route", className: "" },
	{ title: "Vehicle", className: "" },
	{ title: "Driver", className: "" },
	{ title: "Driver number", className: "" },
	{ title: "City", className: "" },
	{ title: "From", className: "" },
	{ title: "To", className: "" },
	{ title: "Action", className: "" },
];

export const USER_MANAGEMENT_HEAD_DATA = [
	{ title: "Name", className: "" },
	{ title: "Role", className: "" },
	{ title: "Mobile number", className: "" },
	{ title: "Email", className: "" },
	{ title: "Action", className: "" },
];

export const DUMMY_DATA = [
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com ",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
	{
		name: "Aqua Fine",
		address: "text",
		person: "Ali Adil",
		email: "ali.adil@aquafine.com",
		contact: "0333-123246",
	},
];

export const EMPLOYEES_DATA = [
	{
		employee: "Alice Johnson",
		email: "alice.johnson@example.com",
		mobileNumber: "+1 555-123-4567",
		city: "New York",
		address: "123 Main St, Apt 4B",
		route: "Route A",
	},
	{
		employee: "Bob Smith",
		email: "bob.smith@example.com",
		mobileNumber: "+1 555-234-5678",
		city: "Los Angeles",
		address: "456 Elm St, Suite 210",
		route: "Route B",
	},
	{
		employee: "Charlie Brown",
		email: "charlie.brown@example.com",
		mobileNumber: "+1 555-345-6789",
		city: "Chicago",
		address: "789 Oak Ave",
		route: "Route C",
	},
	{
		employee: "Diana Prince",
		email: "diana.prince@example.com",
		mobileNumber: "+1 555-456-7890",
		city: "Houston",
		address: "101 Pine St",
		route: "Route D",
	},
	{
		employee: "Ethan Lee",
		email: "ethan.lee@example.com",
		mobileNumber: "+1 555-567-8901",
		city: "Phoenix",
		address: "202 Maple Rd",
		route: "Route E",
	},
	{
		employee: "Fiona Davis",
		email: "fiona.davis@example.com",
		mobileNumber: "+1 555-678-9012",
		city: "Philadelphia",
		address: "303 Cedar Blvd",
		route: "Route F",
	},
	{
		employee: "George Wilson",
		email: "george.wilson@example.com",
		mobileNumber: "+1 555-789-0123",
		city: "San Antonio",
		address: "404 Birch Lane",
		route: "Route G",
	},
	{
		employee: "Hannah Martinez",
		email: "hannah.martinez@example.com",
		mobileNumber: "+1 555-890-1234",
		city: "San Diego",
		address: "505 Walnut Dr",
		route: "Route H",
	},
	{
		employee: "Ian Thompson",
		email: "ian.thompson@example.com",
		mobileNumber: "+1 555-901-2345",
		city: "Dallas",
		address: "606 Spruce Ct",
		route: "Route I",
	},
	{
		employee: "Julia Roberts",
		email: "julia.roberts@example.com",
		mobileNumber: "+1 555-012-3456",
		city: "San Jose",
		address: "707 Willow Way",
		route: "Route J",
	},
];

export const VEHICLES_DATA = [
	{
		registrationNumber: "ABC-123",
		registerWith: "Company A",
		mobileNumber: "+1 555-101-2020",
		registrationCity: "New York",
		address: "123 Main St",
		driver: "John Doe",
	},
	{
		registrationNumber: "XYZ-456",
		registerWith: "Company B",
		mobileNumber: "+1 555-202-3030",
		registrationCity: "Los Angeles",
		address: "456 Elm Ave",
		driver: "Jane Smith",
	},
	{
		registrationNumber: "DEF-789",
		registerWith: "Company C",
		mobileNumber: "+1 555-303-4040",
		registrationCity: "Chicago",
		address: "789 Oak Blvd",
		driver: "Mike Brown",
	},
	{
		registrationNumber: "GHI-012",
		registerWith: "Company D",
		mobileNumber: "+1 555-404-5050",
		registrationCity: "Houston",
		address: "101 Pine Rd",
		driver: "Sara Wilson",
	},
	{
		registrationNumber: "JKL-345",
		registerWith: "Company E",
		mobileNumber: "+1 555-505-6060",
		registrationCity: "Phoenix",
		address: "202 Maple St",
		driver: "David Lee",
	},
	{
		registrationNumber: "MNO-678",
		registerWith: "Company F",
		mobileNumber: "+1 555-606-7070",
		registrationCity: "Philadelphia",
		address: "303 Cedar Dr",
		driver: "Emily Davis",
	},
	{
		registrationNumber: "PQR-901",
		registerWith: "Company G",
		mobileNumber: "+1 555-707-8080",
		registrationCity: "San Antonio",
		address: "404 Birch Ln",
		driver: "Chris Johnson",
	},
	{
		registrationNumber: "STU-234",
		registerWith: "Company H",
		mobileNumber: "+1 555-808-9090",
		registrationCity: "San Diego",
		address: "505 Walnut Ave",
		driver: "Laura Martinez",
	},
	{
		registrationNumber: "VWX-567",
		registerWith: "Company I",
		mobileNumber: "+1 555-909-0101",
		registrationCity: "Dallas",
		address: "606 Spruce Ct",
		driver: "Kevin Thompson",
	},
	{
		registrationNumber: "YZA-890",
		registerWith: "Company J",
		mobileNumber: "+1 555-010-1212",
		registrationCity: "San Jose",
		address: "707 Willow Way",
		driver: "Olivia Roberts",
	},
];

export const ROUTE_DATA = [
	{
		route: "Route 1",
		vehicle: "ABC-123",
		driver: "John Doe",
		driverNumber: "+1 555-101-2020",
		city: "New York",
		from: "Manhattan",
		to: "Brooklyn",
	},
	{
		route: "Route 2",
		vehicle: "XYZ-456",
		driver: "Jane Smith",
		driverNumber: "+1 555-202-3030",
		city: "Los Angeles",
		from: "Downtown",
		to: "Santa Monica",
	},
	{
		route: "Route 3",
		vehicle: "DEF-789",
		driver: "Mike Brown",
		driverNumber: "+1 555-303-4040",
		city: "Chicago",
		from: "Loop",
		to: "Hyde Park",
	},
	{
		route: "Route 4",
		vehicle: "GHI-012",
		driver: "Sara Wilson",
		driverNumber: "+1 555-404-5050",
		city: "Houston",
		from: "Downtown",
		to: "Midtown",
	},
	{
		route: "Route 5",
		vehicle: "JKL-345",
		driver: "David Lee",
		driverNumber: "+1 555-505-6060",
		city: "Phoenix",
		from: "Central City",
		to: "Scottsdale",
	},
	{
		route: "Route 6",
		vehicle: "MNO-678",
		driver: "Emily Davis",
		driverNumber: "+1 555-606-7070",
		city: "Philadelphia",
		from: "Center City",
		to: "University City",
	},
	{
		route: "Route 7",
		vehicle: "PQR-901",
		driver: "Chris Johnson",
		driverNumber: "+1 555-707-8080",
		city: "San Antonio",
		from: "Alamo Heights",
		to: "Downtown",
	},
	{
		route: "Route 8",
		vehicle: "STU-234",
		driver: "Laura Martinez",
		driverNumber: "+1 555-808-9090",
		city: "San Diego",
		from: "Gaslamp Quarter",
		to: "La Jolla",
	},
	{
		route: "Route 9",
		vehicle: "VWX-567",
		driver: "Kevin Thompson",
		driverNumber: "+1 555-909-0101",
		city: "Dallas",
		from: "Downtown",
		to: "Plano",
	},
	{
		route: "Route 10",
		vehicle: "YZA-890",
		driver: "Olivia Roberts",
		driverNumber: "+1 555-010-1212",
		city: "San Jose",
		from: "Downtown",
		to: "Palo Alto",
	},
];

export const USER_MANAGEMENT_DATA = [
	{
		name: "John Doe",
		role: "Admin",
		mobileNumber: "+1 555-101-2020",
		email: "john.doe@example.com",
	},
	{
		name: "Jane Smith",
		role: "Manager",
		mobileNumber: "+1 555-202-3030",
		email: "jane.smith@example.com",
	},
	{
		name: "Mike Brown",
		role: "User",
		mobileNumber: "+1 555-303-4040",
		email: "mike.brown@example.com",
	},
	{
		name: "Sara Wilson",
		role: "Admin",
		mobileNumber: "+1 555-404-5050",
		email: "sara.wilson@example.com",
	},
	{
		name: "David Lee",
		role: "Manager",
		mobileNumber: "+1 555-505-6060",
		email: "david.lee@example.com",
	},
	{
		name: "Emily Davis",
		role: "User",
		mobileNumber: "+1 555-606-7070",
		email: "emily.davis@example.com",
	},
	{
		name: "Chris Johnson",
		role: "Admin",
		mobileNumber: "+1 555-707-8080",
		email: "chris.johnson@example.com",
	},
	{
		name: "Laura Martinez",
		role: "Manager",
		mobileNumber: "+1 555-808-9090",
		email: "laura.martinez@example.com",
	},
	{
		name: "Kevin Thompson",
		role: "User",
		mobileNumber: "+1 555-909-0101",
		email: "kevin.thompson@example.com",
	},
	{
		name: "Olivia Roberts",
		role: "Admin",
		mobileNumber: "+1 555-010-1212",
		email: "olivia.roberts@example.com",
	},
];

export const DUMMY_DRIVER_DATA = [
	{
		name: "John Doe",
		mobile: "03001234567",
		route: "Route 66",
		city: "Lahore",
		email: "john.doe@example.com",
		onboarded: "2024-06-01",
		status: true,
		rating: 4,
	},
	{
		name: "Jane Smith",
		mobile: "03111234567",
		route: "Route 92",
		city: "Karachi",
		email: "jane.smith@example.com",
		onboarded: "2024-05-20",
		status: false,
		rating: 2,
	},
	{
		name: "Ali Khan",
		mobile: "03211234567",
		route: "Route 12",
		city: "Islamabad",
		email: "ali.khan@example.com",
		onboarded: "2024-04-15",
		status: true,
		rating: 5,
	},
	{
		name: "Sara Ahmed",
		mobile: "03331234567",
		route: "Route 7",
		city: "Faisalabad",
		email: "sara.ahmed@example.com",
		onboarded: "2024-03-10",
		status: true,
		rating: 3,
	},
	{
		name: "Usman Iqbal",
		mobile: "03451234567",
		route: "Route 21",
		city: "Multan",
		email: "usman.iqbal@example.com",
		onboarded: "2024-02-05",
		status: false,
		rating: 1,
	},
	{
		name: "Hina Raza",
		mobile: "03561234567",
		route: "Route 33",
		city: "Quetta",
		email: "hina.raza@example.com",
		onboarded: "2024-01-25",
		status: true,
		rating: 5,
	},
	{
		name: "Bilal Saeed",
		mobile: "03671234567",
		route: "Route 9",
		city: "Peshawar",
		email: "bilal.saeed@example.com",
		onboarded: "2024-01-10",
		status: false,
		rating: 2,
	},
	{
		name: "Fatima Noor",
		mobile: "03781234567",
		route: "Route 18",
		city: "Hyderabad",
		email: "fatima.noor@example.com",
		onboarded: "2023-12-15",
		status: true,
		rating: 4,
	},
	{
		name: "Imran Shah",
		mobile: "03891234567",
		route: "Route 27",
		city: "Sialkot",
		email: "imran.shah@example.com",
		onboarded: "2023-11-20",
		status: true,
		rating: 3,
	},
	{
		name: "Ayesha Malik",
		mobile: "03901234567",
		route: "Route 15",
		city: "Gujranwala",
		email: "ayesha.malik@example.com",
		onboarded: "2023-10-05",
		status: false,
		rating: 1,
	},
];
