import "@/lib/init";
import type { Metadata } from "next";
import { Poppins, Inter, DM_Sans } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
	variable: "--font-poppins",
	display: "swap",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const dm_sans = DM_Sans({
	variable: "--font-dm_sans",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "ExecFleet",
	description: "Generated by create next app",
	icons: {
		icon: "/Logo.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${poppins.variable} ${inter.variable} ${dm_sans.variable}  antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
